export const mockStudentData = {
  id: "student-1",
  name: "John Doe",
  rollNumber: "CS-2020-123",
  program: "BS Computer Science",
  batch: "2020-2024",
  cgpa: 3.75,
  semesters: [
    {
      id: "sem-1",
      name: "Semester 1",
      gpa: 3.6,
      courses: [
        {
          id: "course-1",
          name: "Introduction to Programming",
          code: "CS-101",
          marks: 88,
          practicalMarks: 92,
          creditHours: 4,
          teacher: "Dr. Sarah Johnson",
          assistant: "Alex Brown",
        },
        {
          id: "course-2",
          name: "Calculus I",
          code: "MATH-101",
          marks: 82,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Dr. Michael Chen",
          assistant: "Emma Wilson",
        },
        {
          id: "course-3",
          name: "Digital Logic Design",
          code: "CS-102",
          marks: 90,
          practicalMarks: 85,
          creditHours: 4,
          teacher: "Dr. Robert Lee",
          assistant: "David Miller",
        },
        {
          id: "course-4",
          name: "English Composition",
          code: "ENG-101",
          marks: 78,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Prof. Elizabeth Taylor",
          assistant: "Sophie Martin",
        },
      ],
    },
    {
      id: "sem-2",
      name: "Semester 2",
      gpa: 3.8,
      courses: [
        {
          id: "course-5",
          name: "Data Structures",
          code: "CS-201",
          marks: 92,
          practicalMarks: 95,
          creditHours: 4,
          teacher: "Dr. James Wilson",
          assistant: "Oliver Davis",
        },
        {
          id: "course-6",
          name: "Calculus II",
          code: "MATH-201",
          marks: 85,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Dr. Michael Chen",
          assistant: "Emma Wilson",
        },
        {
          id: "course-7",
          name: "Object-Oriented Programming",
          code: "CS-202",
          marks: 94,
          practicalMarks: 90,
          creditHours: 4,
          teacher: "Dr. Sarah Johnson",
          assistant: "Alex Brown",
        },
        {
          id: "course-8",
          name: "Technical Writing",
          code: "ENG-201",
          marks: 82,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Prof. Elizabeth Taylor",
          assistant: "Sophie Martin",
        },
      ],
    },
    {
      id: "sem-3",
      name: "Semester 3",
      gpa: 3.9,
      courses: [
        {
          id: "course-9",
          name: "Database Systems",
          code: "CS-301",
          marks: 95,
          practicalMarks: 92,
          creditHours: 4,
          teacher: "Dr. Robert Lee",
          assistant: "David Miller",
        },
        {
          id: "course-10",
          name: "Linear Algebra",
          code: "MATH-301",
          marks: 88,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Dr. Michael Chen",
          assistant: "Emma Wilson",
        },
        {
          id: "course-11",
          name: "Computer Networks",
          code: "CS-302",
          marks: 90,
          practicalMarks: 88,
          creditHours: 4,
          teacher: "Dr. James Wilson",
          assistant: "Oliver Davis",
        },
        {
          id: "course-12",
          name: "Professional Ethics",
          code: "HUM-301",
          marks: 85,
          practicalMarks: 0,
          creditHours: 2,
          teacher: "Prof. Elizabeth Taylor",
          assistant: "Sophie Martin",
        },
      ],
    },
    {
      id: "sem-4",
      name: "Semester 4",
      gpa: 3.7,
      courses: [
        {
          id: "course-13",
          name: "Operating Systems",
          code: "CS-401",
          marks: 87,
          practicalMarks: 90,
          creditHours: 4,
          teacher: "Dr. Sarah Johnson",
          assistant: "Alex Brown",
        },
        {
          id: "course-14",
          name: "Probability & Statistics",
          code: "MATH-401",
          marks: 82,
          practicalMarks: 0,
          creditHours: 3,
          teacher: "Dr. Michael Chen",
          assistant: "Emma Wilson",
        },
        {
          id: "course-15",
          name: "Software Engineering",
          code: "CS-402",
          marks: 91,
          practicalMarks: 88,
          creditHours: 4,
          teacher: "Dr. Robert Lee",
          assistant: "David Miller",
        },
        {
          id: "course-16",
          name: "Web Development",
          code: "CS-403",
          marks: 94,
          practicalMarks: 96,
          creditHours: 3,
          teacher: "Dr. James Wilson",
          assistant: "Oliver Davis",
        },
      ],
    },
  ],
}
